package com.mehmetyurekli.Util;

public enum ContentChange {
    SETTINGS_EXIT,
    SETTINGS_ENTER,
    CREATE_POST_ENTER,
    CREATE_POST_EXIT,
    OTHER_PROFILE_ENTER_QUERY,
    OTHER_PROFILE_ENTER_FRIENDS,
    PROFILE_ENTER,
    QUERY_ENTER,
    APP_OPEN,
    FRIEND_REQUEST,
    NOTIFICATIONS_ENTER,
    NOTIFICATION_CHANGE,
    FRIEND_REMOVE,
    FRIEND_UPDATE;
}
