package com.mehmetyurekli.Util;

public enum ContentChange { //content change type enum
    SETTINGS_EXIT,
    SETTINGS_ENTER,
    OTHER_PROFILE_ENTER_QUERY,
    OTHER_PROFILE_ENTER_FRIENDS,
    PROFILE_ENTER,
    QUERY_ENTER,
    FRIEND_REQUEST,
    NOTIFICATIONS_ENTER,
    NOTIFICATION_CHANGE,
    FRIEND_UPDATE,
    POST_CREATOR_ENTER,
    FEED_ENTER
}
